'------------------------------------------------------------------------------
' <auto-generated>
'     Este código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.34014
'
'     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
'     o código for regenerado.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Esta classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    'através de uma ferramenta como o ResGen ou o Visual Studio.
    'Para adicionar ou remover um membro, edite o ficheiro .ResX e volte a executar o ResGen
    'com a opção /str ou reconstrua o projecto do VS.
    '''<summary>
    '''  Uma classe de recursos com tipo seguro para procurar cadeias localizadas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devolve a instância ResourceManager em cache utilizada para esta classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ClinicaInformatica.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Substitui a propriedade CurrentUICulture do thread actual para todas as
        '''  pesquisas de recursos que utilizem esta classe de recurso com tipo seguro.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ajuda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ajuda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property BD() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BD", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property company() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("company", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property companyicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("companyicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Entrar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Entrar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fundo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fundo_MDI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundo_MDI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fundo_melhorado_960x540() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundo_melhorado_960x540", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fundoclinica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundoclinica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icone_programa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icone_programa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property oie_2417311E0OBPz25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oie_2417311E0OBPz25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property oie_301011418NFe0o9M() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oie_301011418NFe0o9M", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property oie_301011418NFe0o9M1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oie_301011418NFe0o9M1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property oie_30101423KaMIRkur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oie_30101423KaMIRkur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property oie_30101554lClK1zzf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oie_30101554lClK1zzf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property oie_30101754Hz7aSVUe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oie_30101754Hz7aSVUe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property oie_3010633jb6OZwQ5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oie_3010633jb6OZwQ5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property oie_3010633jb6OZwQ51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oie_3010633jb6OZwQ51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property oie_transparent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oie_transparent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property repair() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("repair", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Procura um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sair() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sair", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
